[package]
name = "qipi"
description = "🦉 The blazing-fast, disk-efficient package manager."
authors = ["Nehuén <https://github.com/nehu3n>"]
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
cli = { path = "crates/cli" }
tokio = { version = "1.42.0", features = ["full"] }
