[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
futures = "0.3.31"
regex = "1.11.1"
shared = { path = "../shared" }
client = { path = "../client" }
