[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
regex = "1.11.1"
client = { path = "../client" }
futures = "0.3.31"
resolver = { path = "../resolver" }